#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Generate docker-compose.override.yml with extra copies of the web apps to
    demonstrate Single Sign-On (SSO). PowerShell twin of generate-webapp-copies.sh.

.DESCRIPTION
    The copy counts are the TOTAL number of instances of each app (1 = base app
    only, no extra copies). Extra copies run on incrementing host ports and share
    a single Keycloak login.

        RTI (OIDC SPA):   base http://rti1.localhost:3000, copies rti2:3001, rti3:3002, ...
        SI  (SAML app):   base http://si1.localhost:4000, copies si2:4001, si3:4002, ...

    Counts are resolved in this order: -RtiCopies/-SiCopies params, then the
    WEBAPP_RTI_COPIES / WEBAPP_SI_COPIES environment variables, then .env, then 1.

.EXAMPLE
    ./generate-webapp-copies.ps1 -RtiCopies 3 -SiCopies 2
#>
param(
    [int]$RtiCopies = -1,
    [int]$SiCopies = -1
)

$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot
$envFile = Join-Path $root '.env'
$overrideFile = Join-Path $root 'docker-compose.override.yml'

function Resolve-Count([int]$paramValue, [string]$name) {
    if ($paramValue -ge 0) { return [Math]::Max(1, $paramValue) }
    $parsed = 0
    $fromEnv = [Environment]::GetEnvironmentVariable($name)
    if ($fromEnv -and [int]::TryParse($fromEnv, [ref]$parsed)) { return [Math]::Max(1, $parsed) }
    if (Test-Path $envFile) {
        $match = Select-String -Path $envFile -Pattern "^\s*$name\s*=\s*(.+?)\s*$" | Select-Object -First 1
        if ($match -and [int]::TryParse($match.Matches[0].Groups[1].Value, [ref]$parsed)) {
            return [Math]::Max(1, $parsed)
        }
    }
    return 1
}

$RtiCopies = Resolve-Count $RtiCopies 'WEBAPP_RTI_COPIES'
$SiCopies = Resolve-Count $SiCopies 'WEBAPP_SI_COPIES'

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('# AUTO-GENERATED by generate-webapp-copies.(sh|ps1) - do not edit by hand.')
[void]$sb.AppendLine("# Extra web app copies for the SSO demo (RTI copies=$RtiCopies, SI copies=$SiCopies).")
[void]$sb.AppendLine('# Regenerate after changing WEBAPP_RTI_COPIES / WEBAPP_SI_COPIES.')

$body = [System.Text.StringBuilder]::new()
$hasCopies = $false

for ($j = 2; $j -le $RtiCopies; $j++) {
    $hasCopies = $true
    $port = 3000 + $j - 1
    [void]$body.AppendLine("  webapp-rti-oauth2-$j`:")
    [void]$body.AppendLine('    build:')
    [void]$body.AppendLine('      context: ./webapp-rti-oauth2')
    [void]$body.AppendLine('      dockerfile: Dockerfile')
    [void]$body.AppendLine('    image: lab/webapp-rti-oauth2:local')
    [void]$body.AppendLine('    environment:')
    [void]$body.AppendLine('      VITE_OIDC_AUTHORITY: ${WEBAPP_A_OIDC_AUTHORITY:-http://rti.localhost:8081/realms/rti}')
    [void]$body.AppendLine("      VITE_OIDC_CLIENT_ID: webapp-rti-oauth2-$j")
    [void]$body.AppendLine("      VITE_OIDC_REDIRECT_URI: http://rti$j.localhost:$port")
    [void]$body.AppendLine('      VITE_API_BASE_URL: ${WEBAPP_A_API_BASE_URL:-http://localhost:5000}')
    [void]$body.AppendLine("      VITE_APP_INSTANCE: `"$j`"")
    [void]$body.AppendLine('    ports:')
    [void]$body.AppendLine("      - `"$port`:3000`"")
    [void]$body.AppendLine('    networks:')
    [void]$body.AppendLine('      - lab-network')
    [void]$body.AppendLine('    depends_on:')
    [void]$body.AppendLine('      keycloak-rti:')
    [void]$body.AppendLine('        condition: service_healthy')
    [void]$body.AppendLine('      keycloak-init:')
    [void]$body.AppendLine('        condition: service_completed_successfully')
    [void]$body.AppendLine('      keycloak-federation-init:')
    [void]$body.AppendLine('        condition: service_completed_successfully')
}

for ($j = 2; $j -le $SiCopies; $j++) {
    $hasCopies = $true
    $port = 4000 + $j - 1
    [void]$body.AppendLine("  webapp-si-saml-backend-$j`:")
    [void]$body.AppendLine('    build:')
    [void]$body.AppendLine('      context: ./webapp-si-saml/backend')
    [void]$body.AppendLine('      dockerfile: Dockerfile')
    [void]$body.AppendLine('    image: lab/webapp-si-saml-backend:local')
    [void]$body.AppendLine('    environment:')
    [void]$body.AppendLine('      PORT: "4001"')
    [void]$body.AppendLine("      FRONTEND_URL: http://si$j.localhost:$port")
    [void]$body.AppendLine('      SAML_ENTRY_POINT: ${WEBAPP_B_SAML_ENTRY_POINT:-http://si.localhost:8082/realms/si/protocol/saml}')
    [void]$body.AppendLine('      SAML_IDP_ISSUER: ${WEBAPP_B_SAML_IDP_ISSUER:-http://si.localhost:8082/realms/si}')
    [void]$body.AppendLine("      SAML_ISSUER: webapp-si-saml-$j")
    [void]$body.AppendLine("      SAML_ACS_URL: http://si$j.localhost:$port/saml/acs")
    [void]$body.AppendLine("      SAML_SLS_URL: http://si$j.localhost:$port/saml/sls")
    [void]$body.AppendLine('      SAML_METADATA_URL: ${WEBAPP_B_SAML_METADATA_URL:-http://keycloak-si:8080/realms/si/protocol/saml/descriptor}')
    [void]$body.AppendLine('      SESSION_SECRET: ${WEBAPP_B_SESSION_SECRET:-webapp-si-saml-dev-secret}')
    [void]$body.AppendLine('    networks:')
    [void]$body.AppendLine('      - lab-network')
    [void]$body.AppendLine('    extra_hosts:')
    [void]$body.AppendLine('      - "rti.localhost:host-gateway"')
    [void]$body.AppendLine('      - "si.localhost:host-gateway"')
    [void]$body.AppendLine('    depends_on:')
    [void]$body.AppendLine('      keycloak-si:')
    [void]$body.AppendLine('        condition: service_healthy')
    [void]$body.AppendLine('      keycloak-init:')
    [void]$body.AppendLine('        condition: service_completed_successfully')
    [void]$body.AppendLine('      keycloak-federation-init:')
    [void]$body.AppendLine('        condition: service_completed_successfully')
    [void]$body.AppendLine("  webapp-si-saml-frontend-$j`:")
    [void]$body.AppendLine('    build:')
    [void]$body.AppendLine('      context: ./webapp-si-saml/frontend')
    [void]$body.AppendLine('      dockerfile: Dockerfile')
    [void]$body.AppendLine('    image: lab/webapp-si-saml-frontend:local')
    [void]$body.AppendLine('    environment:')
    [void]$body.AppendLine("      BACKEND_URL: http://webapp-si-saml-backend-$j`:4001")
    [void]$body.AppendLine("      VITE_APP_INSTANCE: `"$j`"")
    [void]$body.AppendLine('    ports:')
    [void]$body.AppendLine("      - `"$port`:4000`"")
    [void]$body.AppendLine('    networks:')
    [void]$body.AppendLine('      - lab-network')
    [void]$body.AppendLine('    depends_on:')
    [void]$body.AppendLine("      webapp-si-saml-backend-$j`:")
    [void]$body.AppendLine('        condition: service_started')
}

if ($hasCopies) {
    [void]$sb.AppendLine('services:')
    [void]$sb.Append($body.ToString())
} else {
    [void]$sb.AppendLine('services: {}')
}

# LF line endings so the file is identical to the bash-generated one.
$text = $sb.ToString() -replace "`r`n", "`n"
[System.IO.File]::WriteAllText($overrideFile, $text)

Write-Host "Wrote $overrideFile (RTI instances=$RtiCopies, SI instances=$SiCopies)."
if ($hasCopies) {
    if ($RtiCopies -gt 1) { Write-Host "RTI copies on ports:" ((2..$RtiCopies | ForEach-Object { 3000 + $_ - 1 }) -join ', ') }
    if ($SiCopies -gt 1) { Write-Host "SI  copies on ports:" ((2..$SiCopies | ForEach-Object { 4000 + $_ - 1 }) -join ', ') }
} else {
    Write-Host "No extra copies requested (both counts are 1)."
}
